// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: accounts.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const getAccount = `-- name: GetAccount :one
SELECT id, username, email, hashed_password, created_at, updated_at, last_logged_in, privilege_level, restriction_level, restriction_expiry, verified
FROM users.accounts
WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id uuid.UUID) (*UsersAccount, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i UsersAccount
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoggedIn,
		&i.PrivilegeLevel,
		&i.RestrictionLevel,
		&i.RestrictionExpiry,
		&i.Verified,
	)
	return &i, err
}
