name: morpheus

services:
  db:
    image: postgres:15-alpine
    restart: always
    user: postgres
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: kiwiframe
    networks:
      - server-side
    expose:
      - 5432
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -d kiwiframe -U backend' ]
      interval: 1s
      timeout: 5s
      retries: 10

networks:
  client-side: { }
  server-side: { }

volumes:
  db-data: { }
